apiVersion: projectcalico.org/v3
items:
- apiVersion: projectcalico.org/v3
  kind: IPPool
  metadata:
    creationTimestamp: "2020-09-07T17:46:40Z"
    name: default-ipv4-ippool
    resourceVersion: "578"
    uid: 1e3e5da2-ec9f-4d30-9b5e-eb6185aee4be
  spec:
    blockSize: 26
    cidr: 192.168.0.0/16
    ipipMode: Always
    natOutgoing: true
    nodeSelector: all()
    vxlanMode: Never
    disabled: true
- apiVersion: projectcalico.org/v3
  kind: IPPool
  metadata:
    creationTimestamp: "2020-09-18T17:15:51Z"
    name: new-ipv4-ippool
    resourceVersion: "257957"
    uid: 2ccba61f-25e7-4201-8a0e-4a4f07d5843c
  spec:
    blockSize: 26
    cidr: 10.0.0.0/16
    ipipMode: Always
    natOutgoing: true
    nodeSelector: all()
    vxlanMode: Never
kind: IPPoolList
metadata:
  resourceVersion: "258093"
